# Use a Python image to run Sphinx
image: python:latest

# Define the "pages" job, which is a reserved name for GitLab Pages
pages:
  stage: deploy
  before_script:
    - pip install -r requirements.txt
    # - pip install -U sphinx sphinx-rtd-theme  # Install Sphinx and a common theme
  script:
    - sphinx-build -b html source public # Build reST files from source into public/
  artifacts:
    paths:
      - public                                # GitLab expects the site in this folder
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH # Only deploy from the main branch
